controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
initial:  # Define initial robot poses.
  - group: left_arm
    pose: left_home
  - group: right_arm
    pose: right_home